# Project-wide settings
project_name: "pokemon-classification"
device: "mps"
dataset: "fcakyon/pokemon-classification"

# Training Hyperparameters
training:
  batch_size: 32
  lr: 0.00006881758157024532
  epochs: 50
  num_classes: 150

#  Model Architecture
model:
  n_layers: 4
  n_filters: [32, 64, 128, 256]
  dropout_rate: 0.3448163262529962
  fc_size: 1024
  kernel_sizes: [3, 3, 3, 3]
  architecture: "CNN"

hpo:
  n_trials: 20
  lr_range: [1e-5, 1e-4]
  dropout_range: [0.1, 0.5]
  layers_range: [2, 4]
  batch_options: [32, 64, 128]
  fc_options: [256, 512, 1024]
